QUESTION 1: Dataset Loading & Exploration

In [ ]:
import pandas as pd

df = pd.read_csv('/heart.csv')

print("\n1. First 5 rows:")
display(df.head(5))


print("\n2. Last 5 rows:")
display(df.tail(5))

print(f"\n3. Dataset Shape: {df.shape[0]} rows and {df.shape[1]} columns")

1. First 5 rows:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

2. Last 5 rows:

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

3. Dataset Shape: 1025 rows and 14 columns

QUESTION 2: Structure & Missing Values

In [ ]:
print("\n1. Column Names:")
print(df.columns.tolist())


print("\n2. Dataset Information:")
df.info()


print("\n3. Missing Values per Column:")
print(df.isnull().sum())

1. Column Names:
['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target']

2. Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

3. Missing Values per Column:
age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

QUESTION 3: Categorical Data Analysis

In [ ]:

heart_disease_counts = df['target'].value_counts()
print("\n1. Heart Disease Status Counts:")
print(f"Without Heart Disease (0): {heart_disease_counts.get(0, 0)}")
print(f"With Heart Disease (1):    {heart_disease_counts.get(1, 0)}")


gender_counts = df['sex'].value_counts()
print("\n2. Gender Counts:")
print(f"Male (1):   {gender_counts.get(1, 0)}")
print(f"Female (0): {gender_counts.get(0, 0)}")

1. Heart Disease Status Counts:
Without Heart Disease (0): 499
With Heart Disease (1):    526

2. Gender Counts:
Male (1):   713
Female (0): 312

QUESTION 4: Data Selection Using iloc

In [ ]:
first_10_rows = df.iloc[0:10]
print("\n1. First 10 rows (iloc[0:10]):")
display(first_10_rows)


age_sex_chol = df.iloc[:, [0, 1, 4]]
print("\n2. Age, Sex, and Cholesterol columns (iloc[:, [0, 1, 4]]):")
display(age_sex_chol.head())


subset_matrix = df.iloc[20:31, 0:5]
print("\n3. Rows 20 to 30, Columns 0 to 4 (iloc[20:31, 0:5]):")
display(subset_matrix)

1. First 10 rows (iloc[0:10]):

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
6,58,1,0,114,318,0,2,140,0,4.4,0,3,1,0
7,55,1,0,160,289,0,0,145,1,0.8,1,1,3,0
8,46,1,0,120,249,0,0,144,0,0.8,2,0,3,0
9,54,1,0,122,286,0,0,116,1,3.2,1,2,2,0

2. Age, Sex, and Cholesterol columns (iloc[:, [0, 1, 4]]):

   age  sex  chol
0   52    1   212
1   53    1   203
2   70    1   174
3   61    1   203
4   62    0   294

3. Rows 20 to 30, Columns 0 to 4 (iloc[20:31, 0:5]):

    age  sex  cp  trestbps  chol
20   60    1   2       140   185
21   67    0   0       106   223
22   45    1   0       104   208
23   63    0   2       135   252
24   42    0   2       120   209
25   61    0   0       145   307
26   44    1   2       130   233
27   58    0   1       136   319
28   56    1   2       130   256
29   55    0   0       180   327
30   44    1   0       120   169

QUESTION 5: Data Filtering Using Conditions

In [ ]:

older_than_50 = df[df['age'] > 50]
print(f"\n1. Patients older than 50: {len(older_than_50)} patients found.")
display(older_than_50.head())


hd_and_high_chol = df[(df['target'] == 1) & (df['chol'] > 240)]
print(f"\n2. Heart disease AND cholesterol > 240: {len(hd_and_high_chol)} patients found.")
display(hd_and_high_chol.head())


combined_conditions = df[(df['age'] > 50) & (df['target'] == 1) & (df['chol'] > 240)]
print(f"\n3. Number of patients satisfying all conditions (Age > 50, Target == 1, Chol > 240): {len(combined_conditions)}")

1. Patients older than 50: 710 patients found.

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

2. Heart disease AND cholesterol > 240: 222 patients found.

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
5,58,0,0,100,248,0,0,122,0,1.0,1,0,2,1
16,51,0,2,140,308,0,0,142,0,1.5,2,1,2,1
18,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1
23,63,0,2,135,252,0,0,172,0,0.0,2,0,2,1
31,50,0,1,120,244,0,1,162,0,1.1,2,0,2,1

3. Number of patients satisfying all conditions (Age > 50, Target == 1, Chol > 240): 143